"use client";

import Link from "next/link";
import { Icon } from "@iconify/react";
import { FormEvent, useState } from "react";

const catalog = ["第一章 绪论", "第二章 心理学研究方法", "第三章 实验设计", "　3.1 实验设计的基本原理", "　3.2 被试间设计", "　3.3 被试内设计", "　3.4 混合设计", "　3.5 实验设计的有效性", "第四章 变量与控制", "第五章 心理测量"];

export default function StudentPage() {
  const [drawerOpen, setDrawerOpen] = useState(true);
  const [question, setQuestion] = useState("");
  const [sent, setSent] = useState<string | null>(null);
  const send = (event: FormEvent) => { event.preventDefault(); const trimmed = question.trim(); if (trimmed) { setSent(trimmed); setQuestion(""); } };
  return <main className="student-app">
    <header className="app-header student-header"><Link href="/student" className="app-brand"><Icon icon="solar:book-2-bold-duotone" /> 知心学堂</Link><span className="header-divider" /><strong>2026 秋 · 实验心理学</strong><span className="header-hint">基于教材的证据化学习</span><div className="header-spacer" /><div className="progress-mini"><span>学习进度：<strong>第三章 · 42%</strong></span><i><b /></i></div><button className="profile-button"><span className="avatar student-avatar">李</span>李同学 <Icon icon="solar:alt-arrow-down-linear" /></button></header>
    <div className={`student-layout ${drawerOpen ? "drawer-visible" : ""}`}>
      <aside className="catalog-panel"><div className="catalog-head"><strong>教材目录</strong><button aria-label="搜索目录"><Icon icon="solar:magnifer-linear" /></button></div>{catalog.map((item, index) => <button key={item} className={index === 4 ? "catalog-item current" : index === 2 ? "catalog-item expanded" : "catalog-item"}>{index === 2 ? <Icon icon="solar:alt-arrow-down-linear" /> : !item.startsWith("　") ? <Icon icon="solar:alt-arrow-right-linear" /> : <span className="indent" />}{item}<small>{index === 4 ? "本节学习中" : ""}</small></button>)}</aside>
      <section className="reader-panel"><div className="reader-toolbar"><button><Icon icon="solar:alt-arrow-left-linear" /></button><button><Icon icon="solar:alt-arrow-right-linear" /></button><strong>42</strong><span>/386</span><span className="toolbar-space" /><button><Icon icon="solar:minus-circle-linear" /></button><span>100%</span><button><Icon icon="solar:add-circle-linear" /></button><button><Icon icon="solar:bookmark-linear" /> 添加书签</button></div><article className="student-page"><div className="page-running-head"><span>42</span><span>第三章　实验设计</span></div><h1>3.2　被试间设计</h1><p>被试间设计（between-subjects design）是指不同的被试分别接受不同的实验条件，每个被试只参加一种实验条件。与被试内设计相比，被试间设计在程序上相对简单，且不会产生练习效应、疲劳效应和顺序效应，因此在许多研究中被广泛采用。</p><div className="selected-passage"><p>然而，被试间设计也存在明显的局限性。由于不同实验条件下的被试是不同的个体，个体差异可能会对实验结果产生较大影响。即使在随机分配的情况下，各组被试在能力、动机、性格等方面仍可能存在系统性差异，从而增加误差变异，降低实验的内部效度。</p></div><div className="selection-actions"><button><Icon icon="solar:document-text-linear" />解释这段</button><button className="accent" onClick={() => setDrawerOpen(true)}><Icon icon="solar:chat-round-dots-bold" />局部提问</button><button><Icon icon="solar:pen-new-square-linear" />加入笔记</button></div><p>为了减少个体差异的影响，研究者通常采用随机分配（random assignment）的方法，将被试随机分配到不同的实验条件中。随机分配可以在总体上平衡各组的个体差异，从而提高实验的内部效度。</p><p>被试间设计适用于以下情境：实验处理可能产生持久的影响，难以在同一被试身上重复；实验任务之间存在明显的迁移或干扰；以及研究者希望避免被试在多个条件下的比较过程。</p></article></section>
      <section className="tutor-panel"><header><div><h2>AI 教师</h2><span><Icon icon="solar:verified-check-bold" />教材为准 · 有据可依</span></div><button aria-label="更多对话操作"><Icon icon="solar:menu-dots-linear" /></button></header><div className="chat-scroll"><div className="chat-turn user-turn"><span>我</span><p>被试间设计为什么更容易受个体差异影响？</p></div><div className="chat-turn ai-turn"><span><Icon icon="solar:book-2-bold-duotone" /></span><div><p>不同实验条件下的被试是不同的个体，个体差异可能会影响实验结果。即使采用随机分配，样本量有限时也仍可能存在系统性差异，从而增加误差变异、降低内部效度。</p><div className="citation"><Icon icon="solar:book-bookmark-linear" /><strong>[1]　第42页</strong><span>第三章 实验设计 · 3.2 被试间设计</span><em>“由于不同实验条件下的被试是不同的个体……”</em></div><div className="chat-actions"><button>查看原文</button><button onClick={() => setDrawerOpen(true)}>继续追问</button></div></div></div><div className="chat-turn user-turn"><span>我</span><p>随机分配能保证所有无关变量都相同吗？</p></div><div className="chat-turn ai-turn muted-answer"><span><Icon icon="solar:book-2-bold-duotone" /></span><p>当前教材证据不足，无法确认这一点。教材只说明随机分配有助于降低个体差异的影响。</p></div>{sent && <div className="chat-turn user-turn new-turn"><span>我</span><p>{sent}</p></div>}</div><form className="composer" onSubmit={send}><input value={question} onChange={event => setQuestion(event.target.value)} placeholder="围绕当前教材提问……" aria-label="输入教材问题" /><button type="submit" aria-label="发送问题"><Icon icon="solar:plain-2-bold" /></button></form></section>
      {drawerOpen && <aside className="branch-drawer"><header><div><h2>局部追问 1</h2><span>基于选中文本创建</span></div><button aria-label="关闭局部追问" onClick={() => setDrawerOpen(false)}><Icon icon="solar:close-circle-linear" /></button></header><blockquote>然而，被试间设计也存在明显的局限性。由于不同实验条件下的被试是不同的个体……</blockquote><p className="source-page">来自：第42页</p><button className="drawer-expand" onClick={() => setDrawerOpen(false)}>展开对话</button><button className="bring-back" onClick={() => { setDrawerOpen(false); setSent("请继续解释随机分配与个体差异的关系。"); }}><Icon icon="solar:undo-left-round-linear" />带回主对话</button></aside>}
    </div>
  </main>;
}
