"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Icon } from "@iconify/react";
import { api, ApiError } from "../lib/api";

type Health = { database: string; counts: Record<string, number>; model_calls: { purpose: string; status: string; count: number }[]; attempts_in_progress: number; server_time: string }; type Audit = { id: string; action: string; resource_type: string; resource_id: string; created_at: string };
const message = (reason: unknown) => reason instanceof ApiError ? reason.message : "无法读取管理员状态。";
export default function AdminWorkspace() { const [health, setHealth] = useState<Health | null>(null); const [logs, setLogs] = useState<Audit[]>([]); const [notice, setNotice] = useState(""); const load = () => Promise.all([api<Health>("/admin/health"), api<Audit[]>("/admin/audit-logs?limit=30")]).then(([h, a]) => { setHealth(h); setLogs(a); setNotice(""); }).catch(reason => setNotice(message(reason))); useEffect(() => { void load(); }, []); return <main className="functional-app"><header className="app-header"><Link href="/" className="app-brand"><Icon icon="solar:book-2-bold-duotone" />实验心理学智能学习平台</Link><strong>管理员健康检查</strong><div className="header-spacer" /><button className="secondary-button" onClick={() => void load()}>刷新</button></header><section className="functional-main">{notice && <p className="status-banner">{notice}</p>}{health && <><section className="analytics-strip">{Object.entries(health.counts).map(([name, count]) => <div key={name}><strong>{count}</strong><span>{name}</span></div>)}<div><strong>{health.attempts_in_progress}</strong><span>进行中测验</span></div></section><section className="data-grid"><section className="data-panel"><h2>服务状态</h2><p>数据库：{health.database}</p><p>服务时间：{new Date(health.server_time).toLocaleString("zh-CN")}</p></section><section className="data-panel"><h2>模型调用汇总</h2>{health.model_calls.length ? health.model_calls.map(item => <div className="mini-row" key={`${item.purpose}-${item.status}`}><span><strong>{item.purpose}</strong><small>{item.status}</small></span><em>{item.count}</em></div>) : <p className="empty-state">暂无模型调用记录。</p>}</section></section></>}{!health && !notice && <p className="empty-state">正在读取健康状态…</p>}<section className="data-panel"><h2>最近审计记录</h2>{logs.map(log => <div className="mini-row" key={log.id}><span><strong>{log.action}</strong><small>{log.resource_type} · {new Date(log.created_at).toLocaleString("zh-CN")}</small></span><em>{log.resource_id.slice(-6)}</em></div>)}</section></section></main>; }
