"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Icon } from "@iconify/react";
import { api, ApiError } from "../lib/api";

type Course = { id: string; title: string }; type Assessment = { id: string; title: string; availability: string; ai_policy: string }; type Item = { question_version_id: string; order_no: number; points: number; type: string; stem: string; options?: { key: string; text: string }[] }; type Detail = { id: string; title: string; items: Item[] }; type Result = { score: number | null; grading_status: string; items: { question_version_id: string; points_earned: number | null; explanation?: string }[] };
const fail = (reason: unknown) => reason instanceof ApiError ? reason.message : "请求失败，请稍后重试。";
export default function StudentAssessments() {
  const [courses, setCourses] = useState<Course[]>([]); const [courseId, setCourseId] = useState(""); const [list, setList] = useState<Assessment[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [attemptId, setAttemptId] = useState(""); const [answers, setAnswers] = useState<Record<string, string>>({}); const [versions, setVersions] = useState<Record<string, number>>({}); const [result, setResult] = useState<Result | null>(null); const [notice, setNotice] = useState("");
  const load = async (id = courseId) => { if (!id) return; try { setList(await api<Assessment[]>(`/courses/${id}/assessments`)); } catch (reason) { setNotice(fail(reason)); } };
  useEffect(() => { api<Course[]>("/courses").then(data => { setCourses(data); setCourseId(data[0]?.id ?? ""); }).catch(reason => setNotice(fail(reason))); }, []); useEffect(() => { void load(); }, [courseId]);
  async function open(item: Assessment) { try { const [assessment, attempt] = await Promise.all([api<Detail>(`/assessments/${item.id}`), api<{ attempt_id: string }>(`/assessments/${item.id}/attempts`, { method: "POST" })]); setDetail(assessment); setAttemptId(attempt.attempt_id); setAnswers({}); setVersions({}); setResult(null); } catch (reason) { setNotice(fail(reason)); } }
  async function save(questionId: string, key: string) { if (!attemptId) return; setAnswers(items => ({ ...items, [questionId]: key })); try { const response = await api<{ answer_version: number }>(`/attempts/${attemptId}/answers/${questionId}`, { method: "PUT", body: JSON.stringify({ answer_version: versions[questionId] ?? 1, response: { selected_keys: [key] }, client_saved_at: new Date().toISOString() }) }); setVersions(items => ({ ...items, [questionId]: response.answer_version + 1 })); } catch (reason) { setNotice(fail(reason)); } }
  async function submit() { try { await api(`/attempts/${attemptId}/submit`, { method: "POST" }); setResult(await api<Result>(`/attempts/${attemptId}/result`)); } catch (reason) { setNotice(fail(reason)); } }
  return <main className="functional-app"><header className="app-header"><Link href="/" className="app-brand"><Icon icon="solar:book-2-bold-duotone" />实验心理学智能学习平台</Link><Link href="/student">教材学习</Link><strong>测验</strong></header><div className="functional-layout"><aside className="functional-nav"><strong>课程</strong>{courses.map(course => <button className={course.id === courseId ? "data-nav active" : "data-nav"} key={course.id} onClick={() => setCourseId(course.id)}>{course.title}</button>)}</aside><section className="functional-main"><div className="section-title"><div><p className="eyebrow">服务端时间与策略为准</p><h1>课程测验</h1><p>保存、提交和评分都由服务端校验；正式考试可由教师禁用 AI。</p></div></div>{notice && <p className="status-banner">{notice}</p>}{!detail && <section className="data-panel"><h2>可参加测验</h2>{list.length ? list.map(item => <article className="question-card" key={item.id}><div><strong>{item.title}</strong><small>{item.availability} · {item.ai_policy}</small></div><button className="primary-button" onClick={() => void open(item)}>开始或继续</button></article>) : <p className="empty-state">当前没有开放测验。</p>}</section>}{detail && !result && <section className="data-panel"><h2>{detail.title}</h2>{detail.items.map(item => <article className="assessment-item" key={item.question_version_id}><strong>{item.order_no}. {item.stem}</strong>{item.options?.map(option => <label className="check-row" key={option.key}><input type="radio" name={item.question_version_id} checked={answers[item.question_version_id] === option.key} onChange={() => void save(item.question_version_id, option.key)} />{option.key}. {option.text}</label>)}</article>)}<button className="primary-button" onClick={() => void submit()}>提交测验</button></section>}{result && <section className="data-panel"><h2>测验结果</h2><p className="result-score">得分：{result.score ?? "待教师评分"}</p><p>评分状态：{result.grading_status}</p>{result.items.map(item => <div className="mini-row" key={item.question_version_id}><span><strong>{item.points_earned ?? "—"} 分</strong><small>{item.explanation ?? "暂无可显示解析"}</small></span></div>)}<button className="secondary-button" onClick={() => { setDetail(null); setResult(null); void load(); }}>返回测验列表</button></section>}</section></div></main>;
}
