"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Icon } from "@iconify/react";
import { api, ApiError } from "../lib/api";

type Assessment = { id: string; title: string; availability: string; ai_policy: string };
type Question = { question_version_id: string; order_no: number; points: number; type: string; stem: string; options?: { key: string; text: string }[] };
type AssessmentDetail = { id: string; title: string; items: Question[] };
type Result = { score: number | null; grading_status: string; items: { question_version_id: string; points_earned: number | null; explanation?: string }[] };
type Review = { id: string; reason: string; due_at: string };
type Mastery = { knowledge_point: string; state: string; correct_ratio: number };
type MemoryItem = { id?: string; kind?: string; status?: string; created_at?: string; summary?: string };
function message(reason: unknown): string { return reason instanceof ApiError ? reason.message : "请求未完成，请检查本地服务后重试。"; }

export function StudentPracticePage() {
  const { courseId } = useParams<{ courseId: string }>();
  const [assessments, setAssessments] = useState<Assessment[]>([]); const [reviews, setReviews] = useState<Review[]>([]); const [detail, setDetail] = useState<AssessmentDetail | null>(null); const [attemptId, setAttemptId] = useState(""); const [answers, setAnswers] = useState<Record<string, string>>({}); const [versions, setVersions] = useState<Record<string, number>>({}); const [result, setResult] = useState<Result | null>(null); const [notice, setNotice] = useState("正在读取练习…");
  const load = useCallback(() => Promise.all([api<Assessment[]>(`/courses/${courseId}/assessments`), api<Review[]>("/review-tasks?due_only=false")]).then(([nextAssessments, nextReviews]) => { setAssessments(nextAssessments); setReviews(nextReviews); setNotice(""); }).catch((reason) => setNotice(message(reason))), [courseId]);
  useEffect(() => { void load(); }, [load]);
  async function completeReview(task: Review) { try { await api(`/review-tasks/${task.id}/complete`, { method: "POST" }); setReviews((items) => items.filter((item) => item.id !== task.id)); } catch (reason) { setNotice(message(reason)); } }
  async function open(assessment: Assessment) { try { const [nextDetail, attempt] = await Promise.all([api<AssessmentDetail>(`/assessments/${assessment.id}`), api<{ attempt_id: string }>(`/assessments/${assessment.id}/attempts`, { method: "POST" })]); setDetail(nextDetail); setAttemptId(attempt.attempt_id); setAnswers({}); setVersions({}); setResult(null); } catch (reason) { setNotice(message(reason)); } }
  async function save(questionId: string, selected: string) { if (!attemptId) return; setAnswers((items) => ({ ...items, [questionId]: selected })); try { const response = await api<{ answer_version: number }>(`/attempts/${attemptId}/answers/${questionId}`, { method: "PUT", body: JSON.stringify({ answer_version: versions[questionId] ?? 1, response: { selected_keys: [selected] }, client_saved_at: new Date().toISOString() }) }); setVersions((items) => ({ ...items, [questionId]: response.answer_version + 1 })); } catch (reason) { setNotice(message(reason)); } }
  async function submit() { try { await api(`/attempts/${attemptId}/submit`, { method: "POST" }); setResult(await api<Result>(`/attempts/${attemptId}/result`)); } catch (reason) { setNotice(message(reason)); } }
  return <div className="student-support-page"><div className="page-heading"><div><h1>练习</h1><p>在这里完成开放测验和待复习任务。</p></div></div>{notice && <p className="status-banner">{notice}</p>}{!detail ? <div className="practice-grid"><section className="support-panel"><div className="panel-heading"><h2>待复习</h2><span>{reviews.length} 项</span></div>{reviews.length ? reviews.map((review) => <article className="review-row" key={review.id}><span><strong>{review.reason}</strong><small>截止：{new Date(review.due_at).toLocaleDateString("zh-CN")}</small></span><button className="secondary-button" onClick={() => void completeReview(review)}>标记完成</button></article>) : <p className="empty-state">暂无待复习任务。</p>}</section><section className="support-panel"><div className="panel-heading"><h2>开放测验</h2><span>{assessments.length} 个</span></div>{assessments.length ? assessments.map((assessment) => <article className="review-row" key={assessment.id}><span><strong>{assessment.title}</strong><small>{assessment.availability}</small></span><button className="primary-button" onClick={() => void open(assessment)}>开始或继续</button></article>) : <p className="empty-state">当前没有可参加的测验。</p>}</section></div> : !result ? <section className="attempt-panel"><div className="attempt-header"><div><h2>{detail.title}</h2><p>作答将自动保存；提交后由服务端评分。</p></div><span>{Object.keys(answers).length} / {detail.items.length} 已作答</span></div>{detail.items.map((item) => <article className="attempt-question" key={item.question_version_id}><strong>{item.order_no}. {item.stem}</strong>{item.options?.map((option) => <label key={option.key}><input type="radio" name={item.question_version_id} checked={answers[item.question_version_id] === option.key} onChange={() => void save(item.question_version_id, option.key)} />{option.key}. {option.text}</label>)}</article>)}<div className="attempt-actions"><button className="secondary-button" onClick={() => setDetail(null)}>返回练习</button><button className="primary-button" onClick={() => void submit()}>提交测验</button></div></section> : <section className="attempt-panel result-panel"><Icon icon="solar:check-circle-bold" /><h2>测验完成</h2><strong>{result.score ?? "待教师评分"}</strong><p>评分状态：{result.grading_status}</p>{result.items.map((item) => <article className="result-row" key={item.question_version_id}><span>本题得分：{item.points_earned ?? "—"}</span><small>{item.explanation ?? "暂无可显示解析"}</small></article>)}<button className="secondary-button" onClick={() => { setDetail(null); setResult(null); void load(); }}>返回练习</button></section>}</div>;
}

export function StudentGrowthPage() {
  const { courseId } = useParams<{ courseId: string }>(); const [mastery, setMastery] = useState<Mastery[]>([]); const [reviews, setReviews] = useState<Review[]>([]); const [notice, setNotice] = useState("正在读取成长信息…");
  useEffect(() => { Promise.all([api<Mastery[]>(`/me/mastery?course_id=${courseId}`), api<Review[]>("/review-tasks?due_only=false")]).then(([nextMastery, nextReviews]) => { setMastery(nextMastery); setReviews(nextReviews); setNotice(""); }).catch((reason) => setNotice(message(reason))); }, [courseId]);
  return <div className="student-support-page"><div className="page-heading"><div><h1>成长</h1><p>根据你的学习与练习记录，查看当前掌握情况和待复习任务。</p></div></div>{notice && <p className="status-banner">{notice}</p>}<section className="support-panel growth-panel"><div className="panel-heading"><h2>掌握情况</h2><span>{mastery.length} 项</span></div>{mastery.length ? mastery.map((item) => <div className="growth-row" key={item.knowledge_point}><span><strong>{item.knowledge_point}</strong><small>{item.state}</small></span><i><b style={{ width: `${Math.round(item.correct_ratio * 100)}%` }} /></i><em>{Math.round(item.correct_ratio * 100)}%</em></div>) : <p className="empty-state">完成学习或测验后，这里会显示你的掌握情况。</p>}</section><section className="support-panel"><div className="panel-heading"><h2>复习安排</h2><span>{reviews.length} 项</span></div>{reviews.length ? reviews.map((review) => <div className="overview-row" key={review.id}><span><strong>{review.reason}</strong><small>截止：{new Date(review.due_at).toLocaleDateString("zh-CN")}</small></span></div>) : <p className="empty-state">当前没有待复习任务。</p>}</section></div>;
}

export function StudentMePage() {
  const [summary, setSummary] = useState<Record<string, unknown> | null>(null); const [items, setItems] = useState<MemoryItem[]>([]); const [notice, setNotice] = useState("正在读取个人学习信息…"); const [deleting, setDeleting] = useState(false);
  const load = () => Promise.all([api<Record<string, unknown>>("/me/memory"), api<MemoryItem[]>("/me/memory/items?limit=20")]).then(([nextSummary, nextItems]) => { setSummary(nextSummary); setItems(nextItems); setNotice(""); }).catch((reason) => setNotice(message(reason)));
  useEffect(() => { void load(); }, []);
  async function erase() { if (!window.confirm("提交后将停用账号并按学校制度处理学习数据，是否继续？")) return; try { setDeleting(true); const result = await api<{ note: string }>("/me/privacy/delete-request", { method: "POST" }); setNotice(result.note); } catch (reason) { setNotice(message(reason)); } finally { setDeleting(false); } }
  const summaryEntries = summary ? Object.entries(summary).filter(([, value]) => typeof value === "string" || typeof value === "number") : [];
  return <div className="student-support-page"><div className="page-heading"><div><h1>我的</h1><p>查看系统保存给你的学习摘要，并管理隐私删除请求。</p></div></div>{notice && <p className="status-banner">{notice}</p>}<div className="practice-grid"><section className="support-panel"><div className="panel-heading"><h2>学习摘要</h2></div>{summaryEntries.length ? summaryEntries.map(([label, value]) => <div className="overview-row" key={label}><span><strong>{label}</strong><small>{String(value)}</small></span></div>) : <p className="empty-state">暂无可展示的学习摘要。</p>}</section><section className="support-panel"><div className="panel-heading"><h2>隐私</h2></div><div className="privacy-card"><Icon icon="solar:shield-warning-linear" /><div><strong>提交隐私删除请求</strong><p>该请求会停用账号，并按学校制度处理你的学习数据。</p></div><button className="secondary-button" disabled={deleting} onClick={() => void erase()}>{deleting ? "正在提交" : "提交请求"}</button></div></section></div><section className="support-panel memory-list"><div className="panel-heading"><h2>学习记忆</h2><span>{items.length} 条</span></div>{items.length ? items.map((item, index) => <article className="overview-row" key={item.id ?? index}><span><strong>{item.summary || item.kind || "学习记录"}</strong><small>{item.status || "已保存"}{item.created_at ? ` · ${new Date(item.created_at).toLocaleDateString("zh-CN")}` : ""}</small></span></article>) : <p className="empty-state">暂无可展示的学习记录。</p>}</section></div>;
}
