"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Icon } from "@iconify/react";
import { api, ApiError } from "../lib/api";

type Course = { id: string; title: string; term: string };
type Question = { id: string; status: string; version: number; origin: string; current_version?: { id: string; type: string; stem: string; options?: { key: string; text: string }[]; difficulty: number; evidence_ids?: string[] } };
const error = (reason: unknown) => reason instanceof ApiError ? reason.message : "请求失败，请检查服务状态。";

export default function TeacherQuestionBank() {
  const [courses, setCourses] = useState<Course[]>([]); const [courseId, setCourseId] = useState(""); const [questions, setQuestions] = useState<Question[]>([]); const [notice, setNotice] = useState(""); const [creating, setCreating] = useState(false);
  const load = async (id = courseId) => { if (!id) return; try { setQuestions(await api<Question[]>(`/courses/${id}/questions`)); } catch (reason) { setNotice(error(reason)); } };
  useEffect(() => { api<Course[]>("/courses").then(items => { setCourses(items); setCourseId(items[0]?.id ?? ""); }).catch(reason => setNotice(error(reason))); }, []); useEffect(() => { void load(); }, [courseId]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const optionA = String(form.get("a") || "").trim(); const optionB = String(form.get("b") || "").trim(); try { await api(`/courses/${courseId}/questions`, { method: "POST", body: JSON.stringify({ type: "single", stem: form.get("stem"), options: [{ key: "A", text: optionA, is_correct: form.get("correct") === "A" }, { key: "B", text: optionB, is_correct: form.get("correct") === "B" }], explanation: form.get("explanation") || null, difficulty: Number(form.get("difficulty")), knowledge_point_ids: [], evidence_ids: String(form.get("evidence_ids") || "").split(",").map(value => value.trim()).filter(Boolean) }) }); event.currentTarget.reset(); setCreating(false); setNotice("题目已创建为草稿，需审核后发布。"); await load(); } catch (reason) { setNotice(error(reason)); } }
  async function mutate(question: Question, action: "approve" | "reject" | "request_changes" | "publish") { try { if (action === "publish") await api(`/questions/${question.id}/publish`, { method: "POST" }); else await api(`/questions/${question.id}/review`, { method: "POST", body: JSON.stringify({ action, version: question.version, comment: "教师前端审核" }) }); await load(); } catch (reason) { setNotice(error(reason)); } }
  async function generate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const task = await api<{ job_id: string }>(`/courses/${courseId}/question-generation-jobs`, { method: "POST", body: JSON.stringify({ count: Number(form.get("count")), question_types: ["single"], chapter_ids: [], knowledge_point_ids: [] }) }); setNotice(`出题任务已提交：${task.job_id}。完成后刷新题库查看候选草稿。`); } catch (reason) { setNotice(error(reason)); } }
  return <main className="functional-app"><header className="app-header"><Link href="/" className="app-brand"><Icon icon="solar:book-2-bold-duotone" />实验心理学智能学习平台</Link><Link href="/teacher">教材资料</Link><strong>题库与测验</strong><Link href="/teacher/assessments">测验配置</Link></header><div className="functional-layout"><aside className="functional-nav"><strong>课程</strong>{courses.map(course => <button className={course.id === courseId ? "data-nav active" : "data-nav"} key={course.id} onClick={() => setCourseId(course.id)}>{course.title}<small>{course.term}</small></button>)}</aside><section className="functional-main"><div className="section-title"><div><p className="eyebrow">真实题目生命周期</p><h1>题库审核</h1><p>题目会经历草稿、审核和发布；发布前由服务端检查证据绑定。</p></div><button className="primary-button" onClick={() => setCreating(value => !value)}>{creating ? "收起录题" : "录入题目"}</button></div>{notice && <p className="status-banner">{notice}</p>}{creating && <form className="stack-form" onSubmit={create}><textarea name="stem" placeholder="题干" required /><input name="a" placeholder="选项 A" required /><input name="b" placeholder="选项 B" required /><select name="correct" defaultValue="A"><option value="A">正确答案：A</option><option value="B">正确答案：B</option></select><input name="difficulty" type="number" min="1" max="5" defaultValue="2" /><input name="evidence_ids" placeholder="证据 ID（逗号分隔；发布必需）" /><textarea name="explanation" placeholder="解析（可选）" /><button className="primary-button">保存草稿</button></form>}<section className="data-panel"><h2>当前课程题目</h2>{questions.length ? questions.map(question => <article className="question-card" key={question.id}><div><span className="status-chip">{question.status}</span><strong>{question.current_version?.stem ?? "题目版本不可用"}</strong><small>{question.current_version?.type} · 难度 {question.current_version?.difficulty} · {question.origin}</small></div><div className="action-row">{question.status === "draft" ? <button className="secondary-button" onClick={() => void mutate(question, "approve")}>通过审核</button> : null}{question.status === "approved" ? <button className="primary-button" onClick={() => void mutate(question, "publish")}>发布题目</button> : null}</div></article>) : <p className="empty-state">当前课程没有题目。</p>}</section><form className="inline-form" onSubmit={generate}><strong>从教材生成候选题</strong><input name="count" type="number" min="1" max="20" defaultValue="5" /><button className="secondary-button">提交出题任务</button></form></section></div></main>;
}
