"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Icon } from "@iconify/react";
import { api, ApiError } from "../lib/api";

type Course = { id: string; title: string }; type Question = { id: string; status: string; current_version?: { stem: string } }; type Assessment = { id: string; title: string; status: string; availability: string; ai_policy: string };
const failure = (reason: unknown) => reason instanceof ApiError ? reason.message : "请求失败，请稍后重试。";
export default function TeacherAssessments() {
  const [courses, setCourses] = useState<Course[]>([]); const [courseId, setCourseId] = useState(""); const [questions, setQuestions] = useState<Question[]>([]); const [assessments, setAssessments] = useState<Assessment[]>([]); const [selected, setSelected] = useState<string[]>([]); const [notice, setNotice] = useState("");
  const load = async (id = courseId) => { if (!id) return; try { const [qs, as] = await Promise.all([api<Question[]>(`/courses/${id}/questions?status=published`), api<Assessment[]>(`/courses/${id}/assessments`)]); setQuestions(qs); setAssessments(as); setSelected([]); } catch (reason) { setNotice(failure(reason)); } };
  useEffect(() => { api<Course[]>("/courses").then(data => { setCourses(data); setCourseId(data[0]?.id ?? ""); }).catch(reason => setNotice(failure(reason))); }, []); useEffect(() => { void load(); }, [courseId]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (!selected.length) return setNotice("请至少选择一道已发布题目。"); try { await api(`/courses/${courseId}/assessments`, { method: "POST", body: JSON.stringify({ title: form.get("title"), question_ids: selected, ai_policy: form.get("ai_policy"), points_per_question: 1 }) }); setNotice("测验已创建为草稿。请确认后发布。"); event.currentTarget.reset(); await load(); } catch (reason) { setNotice(failure(reason)); } }
  async function publish(id: string) { try { await api(`/assessments/${id}/publish`, { method: "POST" }); setNotice("测验已发布，学生仅会在开放时间内看到题目。"); await load(); } catch (reason) { setNotice(failure(reason)); } }
  return <main className="functional-app"><header className="app-header"><Link href="/" className="app-brand"><Icon icon="solar:book-2-bold-duotone" />实验心理学智能学习平台</Link><Link href="/teacher">教材资料</Link><Link href="/teacher/questions">题库审核</Link><strong>测验配置</strong></header><div className="functional-layout"><aside className="functional-nav"><strong>课程</strong>{courses.map(course => <button key={course.id} className={course.id === courseId ? "data-nav active" : "data-nav"} onClick={() => setCourseId(course.id)}>{course.title}</button>)}</aside><section className="functional-main"><div className="section-title"><div><p className="eyebrow">只使用已发布题目</p><h1>创建与发布测验</h1><p>题目版本会由服务端冻结，学生端不会看到草稿测验。</p></div></div>{notice && <p className="status-banner">{notice}</p>}<div className="data-grid"><section className="data-panel"><h2>选择已发布题目</h2>{questions.length ? questions.map(question => <label className="check-row" key={question.id}><input type="checkbox" checked={selected.includes(question.id)} onChange={() => setSelected(items => items.includes(question.id) ? items.filter(id => id !== question.id) : [...items, question.id])} /><span>{question.current_version?.stem}</span></label>) : <p className="empty-state">暂无已发布题目。请先在题库审核并发布。</p>}</section><section className="data-panel"><h2>新建测验</h2><form className="stack-form" onSubmit={create}><input name="title" placeholder="测验名称" required /><select name="ai_policy" defaultValue="full_after_submit"><option value="disabled">考试中禁用 AI</option><option value="direction_only">仅允许方向提示</option><option value="full_after_submit">提交后完整解析</option></select><p className="empty-state">已选择 {selected.length} 题</p><button className="primary-button">创建草稿测验</button></form></section></div><section className="data-panel"><h2>测验列表</h2>{assessments.length ? assessments.map(item => <article className="question-card" key={item.id}><div><span className="status-chip">{item.status}</span><strong>{item.title}</strong><small>{item.availability} · AI 策略：{item.ai_policy}</small></div>{item.status !== "published" && <button className="primary-button" onClick={() => void publish(item.id)}>发布</button>}</article>) : <p className="empty-state">当前课程尚未创建测验。</p>}</section></section></div></main>;
}
