"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Icon } from "@iconify/react";
import { api, ApiError } from "../lib/api";
type Course={id:string;title:string}; type Member={id:string;user_id:string;display_name:string;role:string;status:string;version?:number}; const fail=(x:unknown)=>x instanceof ApiError?x.message:"请求失败。";
export default function TeacherMembers(){const [courses,setCourses]=useState<Course[]>([]),[courseId,setCourseId]=useState(""),[members,setMembers]=useState<Member[]>([]),[notice,setNotice]=useState("");const load=async(id=courseId)=>{if(!id)return;try{setMembers(await api<Member[]>(`/courses/${id}/members`))}catch(x){setNotice(fail(x))}};// 此 effect 仅请求外部课程列表；状态更新发生在异步响应回调中。
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{api<Course[]>("/courses").then(x=>{setCourses(x);setCourseId(x[0]?.id??"")}).catch(x=>setNotice(fail(x)))},[]);useEffect(()=>{void load()},[courseId]);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const formElement=e.currentTarget;const f=new FormData(formElement);try{await api(`/courses/${courseId}/members`,{method:"POST",body:JSON.stringify({user_id:f.get("user_id"),role:f.get("role")})});formElement.reset();await load()}catch(x){setNotice(fail(x))}}async function remove(m:Member){if(!confirm(`移除 ${m.display_name}？`))return;try{await api(`/courses/${courseId}/members/${m.id}`,{method:"DELETE"});await load()}catch(x){setNotice(fail(x))}}return <main className="functional-app"><header className="app-header"><Link href="/" className="app-brand"><Icon icon="solar:book-2-bold-duotone"/>实验心理学智能学习平台</Link><Link href="/teacher">教材资料</Link><strong>课程成员</strong></header><div className="functional-layout"><aside className="functional-nav">{courses.map(c=><button key={c.id} onClick={()=>setCourseId(c.id)} className={c.id===courseId?"data-nav active":"data-nav"}>{c.title}</button>)}</aside><section className="functional-main"><h1>课程成员</h1>{notice&&<p className="status-banner">{notice}</p>}<form className="inline-form" onSubmit={add}><input name="user_id" placeholder="用户 ULID" required/><select name="role"><option value="student">学生</option><option value="assistant">助教</option><option value="teacher">教师</option></select><button className="primary-button">添加成员</button></form><section className="data-panel">{members.map(m=><div className="mini-row" key={m.id}><span><strong>{m.display_name}</strong><small>{m.role} · {m.user_id}</small></span>{m.role!=="teacher"&&<button onClick={()=>void remove(m)}>移除</button>}</div>)}</section></section></div></main>}
