"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api, ApiError } from "../lib/api";
import {
  assignClassTeacher,
  createCourseClass,
  listClassTeachers,
  listCourseClasses,
  type CourseClass,
  type TeacherAssignment,
} from "../lib/course-api";
import TeacherInterventionsPanel from "./TeacherInterventionsPanel";
import TeacherObservationsPanel from "./TeacherObservationsPanel";
import TeacherGradingPanel from "./TeacherGradingPanel";

type Question = { id: string; status: string; version: number; origin: string; current_version?: { id: string; type: string; stem: string; difficulty: number } };
type Assessment = { id: string; title: string; status: string; availability: string; ai_policy: string };
type Member = { id: string; user_id: string; display_name: string; role: string; status: string };
type Analytics = { participation: { student_count: number; engaged_student_count: number; completed_learning_session_count: number; published_material_count: number }; assessments: { attempt_count: number; participant_count: number; average_score: number | null }; pending_review_task_count: number; chapter_mastery?: { chapter_title: string; average_mastery: number }[]; common_mistakes?: { question_stem: string; incorrect_count: number }[] };
const text = (reason: unknown) => reason instanceof ApiError ? reason.message : "请求未完成，请检查本地服务后重试。";

export function TeacherQuestionsPage() {
  const { courseId } = useParams<{ courseId: string }>(); const [questions, setQuestions] = useState<Question[]>([]); const [notice, setNotice] = useState("正在读取题库…"); const [creating, setCreating] = useState(false);
  const load = useCallback(() => api<Question[]>(`/courses/${courseId}/questions`).then((items) => { setQuestions(items); setNotice(""); }).catch((reason) => setNotice(text(reason))), [courseId]); useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await api(`/courses/${courseId}/questions`, { method: "POST", body: JSON.stringify({ type: "single", stem: form.get("stem"), options: [{ key: "A", text: form.get("a"), is_correct: form.get("correct") === "A" }, { key: "B", text: form.get("b"), is_correct: form.get("correct") === "B" }], explanation: form.get("explanation") || null, difficulty: Number(form.get("difficulty")), knowledge_point_ids: [], evidence_ids: String(form.get("evidence_ids") || "").split(",").map((value) => value.trim()).filter(Boolean) }) }); formElement.reset(); setCreating(false); setNotice("题目已保存为草稿，审核后才能发布。"); await load(); } catch (reason) { setNotice(text(reason)); } }
  async function action(question: Question, kind: "approve" | "publish") { try { if (kind === "publish") await api(`/questions/${question.id}/publish`, { method: "POST" }); else await api(`/questions/${question.id}/review`, { method: "POST", body: JSON.stringify({ action: "approve", version: question.version, comment: "教师审核" }) }); await load(); } catch (reason) { setNotice(text(reason)); } }
  async function generate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const result = await api<{ job_id: string }>(`/courses/${courseId}/question-generation-jobs`, { method: "POST", body: JSON.stringify({ count: Number(form.get("count")), question_types: ["single"], chapter_ids: [], knowledge_point_ids: [] }) }); setNotice(`候选题生成已提交，完成后刷新题库查看草稿（任务 ${result.job_id.slice(-8)}）。`); } catch (reason) { setNotice(text(reason)); } }
  return <div className="teacher-support-page"><div className="page-heading"><div><h1>题库</h1><p>题目先保存为草稿，经教师审核并绑定证据后才能发布。</p></div><button className="primary-button" onClick={() => setCreating((value) => !value)}>{creating ? "收起录题" : "录入题目"}</button></div>{notice && <p className="status-banner">{notice}</p>}{creating && <form className="support-form" onSubmit={create}><textarea name="stem" placeholder="题干" required /><input name="a" placeholder="选项 A" required /><input name="b" placeholder="选项 B" required /><select name="correct" defaultValue="A"><option value="A">正确答案：A</option><option value="B">正确答案：B</option></select><input name="difficulty" type="number" min="1" max="5" defaultValue="2" /><input name="evidence_ids" placeholder="证据 ID（逗号分隔；发布必需）" /><textarea name="explanation" placeholder="解析（可选）" /><button className="primary-button">保存草稿</button></form>}<section className="support-panel teacher-list"><div className="panel-heading"><h2>当前课程题目</h2><span>{questions.length} 道</span></div>{questions.length ? questions.map((question) => <article className="teacher-row" key={question.id}><div><span className={`status-tag ${question.status}`}>{question.status === "published" ? "已发布" : question.status === "approved" ? "已审核" : "草稿"}</span><strong>{question.current_version?.stem ?? "题目版本不可用"}</strong><small>{question.current_version?.type} · 难度 {question.current_version?.difficulty} · {question.origin}</small></div>{question.status === "draft" ? <button className="secondary-button" onClick={() => void action(question, "approve")}>通过审核</button> : question.status === "approved" ? <button className="primary-button" onClick={() => void action(question, "publish")}>发布题目</button> : null}</article>) : <p className="empty-state">当前课程没有题目。</p>}</section><form className="generation-form" onSubmit={generate}><span><strong>从教材生成候选题</strong><small>生成结果仍须人工审核后才能发布。</small></span><input name="count" type="number" min="1" max="20" defaultValue="5" /><button className="secondary-button">提交生成任务</button></form></div>;
}

export function TeacherAssessmentsPage() {
  const { courseId } = useParams<{ courseId: string }>(); const [questions, setQuestions] = useState<Question[]>([]); const [assessments, setAssessments] = useState<Assessment[]>([]); const [selected, setSelected] = useState<string[]>([]); const [notice, setNotice] = useState("正在读取测验…");
  const load = useCallback(() => Promise.all([api<Question[]>(`/courses/${courseId}/questions?status=published`), api<Assessment[]>(`/courses/${courseId}/assessments`)]).then(([nextQuestions, nextAssessments]) => { setQuestions(nextQuestions); setAssessments(nextAssessments); setSelected([]); setNotice(""); }).catch((reason) => setNotice(text(reason))), [courseId]); useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected.length) { setNotice("请至少选择一道已发布题目。"); return; } const formElement = event.currentTarget; const form = new FormData(formElement); try { await api(`/courses/${courseId}/assessments`, { method: "POST", body: JSON.stringify({ title: form.get("title"), question_ids: selected, ai_policy: form.get("ai_policy"), points_per_question: 1 }) }); formElement.reset(); setNotice("测验已创建为草稿，请确认后发布。"); await load(); } catch (reason) { setNotice(text(reason)); } }
  async function publish(id: string) { try { await api(`/assessments/${id}/publish`, { method: "POST" }); setNotice("测验已发布；学生只会在开放时间内看到题目。"); await load(); } catch (reason) { setNotice(text(reason)); } }
  return <div className="teacher-support-page"><div className="page-heading"><div><h1>测验</h1><p>测验只使用已发布题目；发布前，学生看不到草稿。</p></div></div>{notice && <p className="status-banner">{notice}</p>}<div className="assessment-builder"><section className="support-panel"><div className="panel-heading"><h2>选择已发布题目</h2><span>{selected.length} 已选择</span></div>{questions.length ? questions.map((question) => <label className="question-check" key={question.id}><input type="checkbox" checked={selected.includes(question.id)} onChange={() => setSelected((items) => items.includes(question.id) ? items.filter((id) => id !== question.id) : [...items, question.id])} />{question.current_version?.stem}</label>) : <p className="empty-state">暂无已发布题目，请先在题库审核并发布。</p>}</section><section className="support-panel"><div className="panel-heading"><h2>新建测验</h2></div><form className="support-form" onSubmit={create}><input name="title" placeholder="测验名称" required /><select name="ai_policy" defaultValue="full_after_submit"><option value="disabled">考试中禁用 AI</option><option value="direction_only">仅允许方向提示</option><option value="full_after_submit">提交后完整解析</option></select><p className="empty-state">已选择 {selected.length} 道题目</p><button className="primary-button">创建草稿测验</button></form></section></div><section className="support-panel teacher-list"><div className="panel-heading"><h2>测验列表</h2><span>{assessments.length} 个</span></div>{assessments.length ? assessments.map((item) => <article className="teacher-row" key={item.id}><div><span className={`status-tag ${item.status}`}>{item.status === "published" ? "已发布" : "草稿"}</span><strong>{item.title}</strong><small>{item.availability} · AI：{item.ai_policy}</small></div>{item.status !== "published" && <button className="primary-button" onClick={() => void publish(item.id)}>发布测验</button>}</article>) : <p className="empty-state">当前课程尚未创建测验。</p>}</section><TeacherGradingPanel courseId={courseId} /></div>;
}

export function TeacherAnalyticsPage() {
  const { courseId } = useParams<{ courseId: string }>(); const [data, setData] = useState<Analytics | null>(null); const [notice, setNotice] = useState("正在读取学情…"); useEffect(() => { api<Analytics>(`/courses/${courseId}/analytics/overview`).then((next) => { setData(next); setNotice(""); }).catch((reason) => setNotice(text(reason))); }, [courseId]);
  const metrics = data ? [[data.participation.student_count, "在册学生"], [data.participation.engaged_student_count, "参与学习"], [data.assessments.participant_count, "参与测验"], [data.assessments.average_score ?? "—", "测验平均分"], [data.pending_review_task_count, "待完成复习"]] : [];
  return <div className="teacher-support-page"><div className="page-heading"><div><h1>学情</h1><p>展示课程聚合学习情况，不展示学生私聊或个人记忆内容。</p></div></div>{notice && <p className="status-banner">{notice}</p>}{data && <><section className="teacher-metrics">{metrics.map(([value, label]) => <article key={String(label)}><strong>{value}</strong><span>{label}</span></article>)}</section><section className="support-panel"><div className="panel-heading"><h2>课程参与</h2></div><div className="analytics-copy"><p>已完成学习会话：<strong>{data.participation.completed_learning_session_count}</strong></p><p>已发布教材：<strong>{data.participation.published_material_count}</strong></p><p>测验作答次数：<strong>{data.assessments.attempt_count}</strong></p></div></section></>}<TeacherObservationsPanel courseId={courseId} /><TeacherInterventionsPanel courseId={courseId} /></div>;
}

export function TeacherMembersPage() {
  const { courseId } = useParams<{ courseId: string }>(); const [members, setMembers] = useState<Member[]>([]); const [classes, setClasses] = useState<CourseClass[]>([]); const [assignments, setAssignments] = useState<Record<string, TeacherAssignment[]>>({}); const [notice, setNotice] = useState("正在读取成员…"); const load = useCallback(async () => { try { const [nextMembers, nextClasses] = await Promise.all([api<Member[]>(`/courses/${courseId}/members`), listCourseClasses(courseId)]); setMembers(nextMembers); setClasses(nextClasses); const pairs = await Promise.all(nextClasses.map(async (item) => [item.id, await listClassTeachers(courseId, item.id)] as const)); setAssignments(Object.fromEntries(pairs)); setNotice(""); } catch (reason) { setNotice(text(reason)); } }, [courseId]); useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await api(`/courses/${courseId}/members`, { method: "POST", body: JSON.stringify({ user_id: form.get("user_id"), role: form.get("role") }) }); formElement.reset(); await load(); } catch (reason) { setNotice(text(reason)); } }
  async function createClass(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await createCourseClass(courseId, { code: String(form.get("code")), name: String(form.get("name")) }); formElement.reset(); await load(); } catch (reason) { setNotice(text(reason)); } }
  async function assign(classId: string, event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await assignClassTeacher(courseId, classId, { teacher_id: String(form.get("teacher_id")), assignment_role: "lead" }); formElement.reset(); await load(); } catch (reason) { setNotice(text(reason)); } }
  async function remove(member: Member) { if (!window.confirm(`移除 ${member.display_name}？`)) return; try { await api(`/courses/${courseId}/members/${member.id}`, { method: "DELETE" }); await load(); } catch (reason) { setNotice(text(reason)); } }
  const teachers = members.filter((member) => member.role === "teacher" || member.role === "assistant");
  return <div className="teacher-support-page"><div className="page-heading"><div><h1>成员与班级</h1><p>管理当前课程成员，并把已加入课程的教师显式分配到班级。</p></div></div>{notice && <p className="status-banner">{notice}</p>}<form className="member-form" onSubmit={add}><input name="user_id" required placeholder="用户 ID" /><select name="role"><option value="student">学生</option><option value="assistant">助教</option><option value="teacher">教师</option></select><button className="primary-button">添加成员</button></form><section className="support-panel teacher-list"><div className="panel-heading"><h2>课程成员</h2><span>{members.length} 人</span></div>{members.length ? members.map((member) => <article className="teacher-row" key={member.id}><div><strong>{member.display_name}</strong><small>{member.role} · {member.status}</small></div>{member.role !== "teacher" && <button className="secondary-button" onClick={() => void remove(member)}>移除</button>}</article>) : <p className="empty-state">当前课程没有可显示成员。</p>}</section><section className="support-panel teacher-list"><div className="panel-heading"><h2>教学班级</h2><span>{classes.length} 个</span></div><form className="member-form" onSubmit={createClass}><input name="code" required placeholder="班级编码" /><input name="name" required placeholder="班级名称" /><button className="primary-button">创建班级</button></form>{classes.length ? classes.map((item) => <article className="teacher-row" key={item.id}><div><strong>{item.code} · {item.name}</strong><small>{(assignments[item.id] ?? []).map((assignment) => `${assignment.teacher_name}（${assignment.assignment_role}）`).join("、") || "尚未分配教师"}</small><form className="member-form" onSubmit={(event) => void assign(item.id, event)}><select name="teacher_id" required defaultValue=""><option value="" disabled>选择课程教师</option>{teachers.map((teacher) => <option key={teacher.user_id} value={teacher.user_id}>{teacher.display_name} · {teacher.role}</option>)}</select><button className="secondary-button" disabled={!teachers.length}>分配任课</button></form></div></article>) : <p className="empty-state">当前课程暂无班级。</p>}</section></div>;
}
