// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/course-design" | "/course-design/assessment" | "/course-design/assets" | "/course-design/domain" | "/course-design/pedagogy" | "/course-design/releases" | "/login" | "/privacy/deletion-status" | "/student" | "/student/assessments" | "/student/branches" | "/student/courses" | "/student/courses/[courseId]" | "/student/courses/[courseId]/growth" | "/student/courses/[courseId]/learn" | "/student/courses/[courseId]/me" | "/student/courses/[courseId]/practice" | "/student/learning" | "/student/profile" | "/teacher" | "/teacher/assessments" | "/teacher/courses" | "/teacher/courses/[courseId]" | "/teacher/courses/[courseId]/analytics" | "/teacher/courses/[courseId]/assessments" | "/teacher/courses/[courseId]/materials" | "/teacher/courses/[courseId]/members" | "/teacher/courses/[courseId]/questions" | "/teacher/members" | "/teacher/questions"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/course-design" | "/student" | "/student/courses/[courseId]" | "/teacher" | "/teacher/courses/[courseId]"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/course-design": {}
  "/course-design/assessment": {}
  "/course-design/assets": {}
  "/course-design/domain": {}
  "/course-design/pedagogy": {}
  "/course-design/releases": {}
  "/login": {}
  "/privacy/deletion-status": {}
  "/student": {}
  "/student/assessments": {}
  "/student/branches": {}
  "/student/courses": {}
  "/student/courses/[courseId]": { "courseId": string; }
  "/student/courses/[courseId]/growth": { "courseId": string; }
  "/student/courses/[courseId]/learn": { "courseId": string; }
  "/student/courses/[courseId]/me": { "courseId": string; }
  "/student/courses/[courseId]/practice": { "courseId": string; }
  "/student/learning": {}
  "/student/profile": {}
  "/teacher": {}
  "/teacher/assessments": {}
  "/teacher/courses": {}
  "/teacher/courses/[courseId]": { "courseId": string; }
  "/teacher/courses/[courseId]/analytics": { "courseId": string; }
  "/teacher/courses/[courseId]/assessments": { "courseId": string; }
  "/teacher/courses/[courseId]/materials": { "courseId": string; }
  "/teacher/courses/[courseId]/members": { "courseId": string; }
  "/teacher/courses/[courseId]/questions": { "courseId": string; }
  "/teacher/members": {}
  "/teacher/questions": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/course-design": never
  "/student": never
  "/student/courses/[courseId]": never
  "/teacher": never
  "/teacher/courses/[courseId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
