// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/course-design/assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/course-design/assessment">> = Specific
  const handler = {} as typeof import("../../../app/course-design/assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/course-design/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/course-design/assets">> = Specific
  const handler = {} as typeof import("../../../app/course-design/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/course-design/domain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/course-design/domain">> = Specific
  const handler = {} as typeof import("../../../app/course-design/domain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/course-design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/course-design">> = Specific
  const handler = {} as typeof import("../../../app/course-design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/course-design/pedagogy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/course-design/pedagogy">> = Specific
  const handler = {} as typeof import("../../../app/course-design/pedagogy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/course-design/releases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/course-design/releases">> = Specific
  const handler = {} as typeof import("../../../app/course-design/releases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/deletion-status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy/deletion-status">> = Specific
  const handler = {} as typeof import("../../../app/privacy/deletion-status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/assessments">> = Specific
  const handler = {} as typeof import("../../../app/student/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/branches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/branches">> = Specific
  const handler = {} as typeof import("../../../app/student/branches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/courses/[courseId]/growth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/courses/[courseId]/growth">> = Specific
  const handler = {} as typeof import("../../../app/student/courses/[courseId]/growth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/courses/[courseId]/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/courses/[courseId]/learn">> = Specific
  const handler = {} as typeof import("../../../app/student/courses/[courseId]/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/courses/[courseId]/me/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/courses/[courseId]/me">> = Specific
  const handler = {} as typeof import("../../../app/student/courses/[courseId]/me/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/courses/[courseId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/courses/[courseId]">> = Specific
  const handler = {} as typeof import("../../../app/student/courses/[courseId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/courses/[courseId]/practice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/courses/[courseId]/practice">> = Specific
  const handler = {} as typeof import("../../../app/student/courses/[courseId]/practice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/courses">> = Specific
  const handler = {} as typeof import("../../../app/student/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/learning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/learning">> = Specific
  const handler = {} as typeof import("../../../app/student/learning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student">> = Specific
  const handler = {} as typeof import("../../../app/student/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/profile">> = Specific
  const handler = {} as typeof import("../../../app/student/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/assessments">> = Specific
  const handler = {} as typeof import("../../../app/teacher/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/courses/[courseId]/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/courses/[courseId]/analytics">> = Specific
  const handler = {} as typeof import("../../../app/teacher/courses/[courseId]/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/courses/[courseId]/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/courses/[courseId]/assessments">> = Specific
  const handler = {} as typeof import("../../../app/teacher/courses/[courseId]/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/courses/[courseId]/materials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/courses/[courseId]/materials">> = Specific
  const handler = {} as typeof import("../../../app/teacher/courses/[courseId]/materials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/courses/[courseId]/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/courses/[courseId]/members">> = Specific
  const handler = {} as typeof import("../../../app/teacher/courses/[courseId]/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/courses/[courseId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/courses/[courseId]">> = Specific
  const handler = {} as typeof import("../../../app/teacher/courses/[courseId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/courses/[courseId]/questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/courses/[courseId]/questions">> = Specific
  const handler = {} as typeof import("../../../app/teacher/courses/[courseId]/questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/courses">> = Specific
  const handler = {} as typeof import("../../../app/teacher/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/members">> = Specific
  const handler = {} as typeof import("../../../app/teacher/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher">> = Specific
  const handler = {} as typeof import("../../../app/teacher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/questions">> = Specific
  const handler = {} as typeof import("../../../app/teacher/questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/course-design/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/course-design">> = Specific
  const handler = {} as typeof import("../../../app/course-design/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/courses/[courseId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/student/courses/[courseId]">> = Specific
  const handler = {} as typeof import("../../../app/student/courses/[courseId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/student/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/student">> = Specific
  const handler = {} as typeof import("../../../app/student/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/courses/[courseId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/teacher/courses/[courseId]">> = Specific
  const handler = {} as typeof import("../../../app/teacher/courses/[courseId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/teacher/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/teacher">> = Specific
  const handler = {} as typeof import("../../../app/teacher/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
